name: FSMG-Framework
main: com.forgestorm.mgfw.MGFramework
version: 0.1
description: ForgeStorm MiniGame Framework
author: Robert Andrew Brown
website: http://www.forgestorm.com/
depend: [FSCore]
commands:
  admin: